[project]
name = "eden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.12"
dependencies = [
    "openai",
    "pytest",
    "numpy",
    "langchain==0.0.273",
    "langsmith==0.0.41",
    "pydantic==2.7.1"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = [
    "tests"
]
