import pytest                                                                                                                                                                                                
import datetime                                                                                                                                                                                              
import json                                                                                                                                                                                                  
from src.config import openai_api_key, use_openai, api_model

# from src.persona.memory_structures.associative_memory import AssociativeMemory      
from src.persona.memory_structures.new_associative_memory import MemoryNode, VectorMemory                                                                                                                          
from src.persona.prompt_template.gpt_structure import get_embedding        
                                                                                                                                                                                                            
@pytest.fixture                                                                                                                                                                                              
def hot_memory(tmp_path):                                                                                                                                                                                    
    # Create temporary test files                                                                                                                                                                            
    memory_dir = tmp_path / "memory"                                                                                                                                                                         
    memory_dir.mkdir()                                                                                                                                                                                       
                                                                                                                                                                                                            
    # Create empty initial files                                                                                                                                                                             
    embeddings = {}                                                                                                                                                                                          
    nodes = {}                                                                                                                                                                                               
    kw_strength = {"kw_strength_event": {}, "kw_strength_thought": {}}                                                                                                                                       
                                                                                                                                                                                                            
    (memory_dir / "embeddings.json").write_text(json.dumps(embeddings))                                                                                                                                      
    (memory_dir / "nodes.json").write_text(json.dumps(nodes))                                                                                                                                                
    (memory_dir / "kw_strength.json").write_text(json.dumps(kw_strength))                                                                                                                                    
                                                                                                                                                                                                            
    return VectorMemory(str(memory_dir))                                                                                                                                                                
                                                                                                                                                                                                            
@pytest.mark.slow  # Mark these tests as slow since they use real API                                                                                                                                        
def test_retrieve_semantically_similar_events(hot_memory):                                                                                                                                                   
    created = datetime.datetime.now()                                                                                                                                                                        
                                                                                                                                                                                                            
    # Add events with semantic relationships                                                                                                                                                                 
    event1_desc = "John is cooking pasta for dinner in the kitchen"                                                                                                                                          
    event1_embedding = get_embedding(event1_desc)                                                                                                                                                            
    event1 = hot_memory.add_event(                                                                                                                                                                           
        created=created,                                                                                                                                                                                     
        expiration=None,                                                                                                                                                                                     
        s="John",                                                                                                                                                                                            
        p="cooks",                                                                                                                                                                                           
        o="pasta",                                                                                                                                                                                           
        description=event1_desc,                                                                                                                                                                             
        keywords={"cooking", "pasta", "dinner"},                                                                                                                                                             
        poignancy=0.5,                                                                                                                                                                                       
        embedding_pair=("key1", event1_embedding),                                                                                                                                                           
        filling=None                                                                                                                                                                                         
    )                                                                                                                                                                                                        
                                                                                                                                                                                                            
    event2_desc = "Mary is preparing spaghetti with meatballs"                                                                                                                                               
    event2_embedding = get_embedding(event2_desc)                                                                                                                                                            
    event2 = hot_memory.add_event(                                                                                                                                                                           
        created=created,                                                                                                                                                                                     
        expiration=None,                                                                                                                                                                                     
        s="Mary",                                                                                                                                                                                            
        p="prepares",                                                                                                                                                                                        
        o="spaghetti",                                                                                                                                                                                       
        description=event2_desc,                                                                                                                                                                             
        keywords={"cooking", "spaghetti", "meatballs"},                                                                                                                                                      
        poignancy=0.5,                                                                                                                                                                                       
        embedding_pair=("key2", event2_embedding),                                                                                                                                                           
        filling=None                                                                                                                                                                                         
    )                                                                                                                                                                                                        
                                                                                                                                                                                                            
    event3_desc = "Bob is playing tennis at the park"                                                                                                                                                        
    event3_embedding = get_embedding(event3_desc)                                                                                                                                                            
    event3 = hot_memory.add_event(                                                                                                                                                                           
        created=created,                                                                                                                                                                                     
        expiration=None,                                                                                                                                                                                     
        s="Bob",                                                                                                                                                                                             
        p="plays",                                                                                                                                                                                           
        o="tennis",                                                                                                                                                                                          
        description=event3_desc,                                                                                                                                                                             
        keywords={"sports", "tennis", "park"},                                                                                                                                                               
        poignancy=0.5,                                                                                                                                                                                       
        embedding_pair=("key3", event3_embedding),                                                                                                                                                           
        filling=None                                                                                                                                                                                         
    )                                                                                                                                                                                                        
                                                                                                                                                                                                            
    # Test retrieval with semantically similar query                                                                                                                                                         
    query = "Someone is making Italian food"                                                                                                                                                                 
    relevant = hot_memory.retrieve_relevant_events(query, "", "")                                                                                                                                            
                                                                                                                                                                                                            
    # The cooking-related events should be retrieved first                                                                                                                                                   
    assert len(relevant) >= 2                                                                                                                                                                                
    assert event1 in relevant[:2]  # Pasta event should be in top 2                                                                                                                                          
    assert event2 in relevant[:2]  # Spaghetti event should be in top 2                                                                                                                                      
    assert event3 not in relevant[:2]  # Tennis event should not be in top 2                                                                                                                                 
                                                                                                                                                                                                            
@pytest.mark.slow                                                                                                                                                                                            
def test_retrieve_events_with_context_switch(hot_memory):                                                                                                                                                    
    created = datetime.datetime.now()                                                                                                                                                                        
                                                                                                                                                                                                            
    # Add a sequence of related and unrelated events                                                                                                                                                         
    events_data = [                                                                                                                                                                                          
        {                                                                                                                                                                                                    
            "desc": "John enters the library quietly",                                                                                                                                                       
            "s": "John",                                                                                                                                                                                     
            "p": "enters",                                                                                                                                                                                   
            "o": "library",                                                                                                                                                                                  
            "keywords": {"library", "quiet"}                                                                                                                                                                 
        },                                                                                                                                                                                                   
        {                                                                                                                                                                                                    
            "desc": "John picks up a book about history",                                                                                                                                                    
            "s": "John",                                                                                                                                                                                     
            "p": "picks up",                                                                                                                                                                                 
            "o": "book",                                                                                                                                                                                     
            "keywords": {"book", "history"}                                                                                                                                                                  
        },                                                                                                                                                                                                   
        {                                                                                                                                                                                                    
            "desc": "A fire truck races past with sirens blaring",                                                                                                                                           
            "s": "fire truck",                                                                                                                                                                               
            "p": "races",                                                                                                                                                                                    
            "o": "past",                                                                                                                                                                                     
            "keywords": {"emergency", "noise"}                                                                                                                                                               
        },                                                                                                                                                                                                   
        {                                                                                                                                                                                                    
            "desc": "John continues reading in the study area",                                                                                                                                              
            "s": "John",                                                                                                                                                                                     
            "p": "reads",                                                                                                                                                                                    
            "o": "book",                                                                                                                                                                                     
            "keywords": {"reading", "study"}                                                                                                                                                                 
        }                                                                                                                                                                                                    
    ]                                                                                                                                                                                                        
                                                                                                                                                                                                            
    # Add events with real embeddings                                                                                                                                                                        
    added_events = []                                                                                                                                                                                        
    for i, event_data in enumerate(events_data):                                                                                                                                                             
        embedding = get_embedding(event_data["desc"])                                                                                                                                                        
        event = hot_memory.add_event(                                                                                                                                                                        
            created=created + datetime.timedelta(minutes=i),                                                                                                                                                 
            expiration=None,                                                                                                                                                                                 
            s=event_data["s"],                                                                                                                                                                               
            p=event_data["p"],                                                                                                                                                                               
            o=event_data["o"],                                                                                                                                                                               
            description=event_data["desc"],                                                                                                                                                                  
            keywords=event_data["keywords"],                                                                                                                                                                 
            poignancy=0.5,                                                                                                                                                                                   
            embedding_pair=(f"key{i+1}", embedding),                                                                                                                                                         
            filling=None                                                                                                                                                                                     
        )                                                                                                                                                                                                    
        added_events.append(event)                                                                                                                                                                           
                                                                                                                                                                                                            
    # Test retrieval for library-related activities                                                                                                                                                          
    query = "Someone doing quiet activities in a library"                                                                                                                                                    
    relevant = hot_memory.retrieve_relevant_events(query, "", "")                                                                                                                                            
                                                                                                                                                                                                            
    # Library events should be retrieved, fire truck should not be                                                                                                                                           
    assert len(relevant) >= 3                                                                                                                                                                                
    assert added_events[0] in relevant[:3]  # Entering library                                                                                                                                               
    assert added_events[1] in relevant[:3]  # Picking up book                                                                                                                                                
    assert added_events[3] in relevant[:3]  # Reading in study area                                                                                                                                          
    assert added_events[2] not in relevant[:3]  # Fire truck (interruption)
